- name: Install openjdk
  yum: name={{ open_jdk }} state=installed

- name: Enable Logstash repository
  template: src=logstash_repo
            dest={{ logstash_yum_config }}

- name: Add Logstash Repo Key
  rpm_key: key="{{ logstash_repo_key }}" 
           state=present

- name: Install Logstash and Logstash-Contrib
  yum: name={{ item.package }} 
       state=latest
  with_items: logstash_packages

- name: Configure default settings for Logstash
  template: src=defaults.conf
            dest=/etc/sysconfig/logstash
            owner=root
            group=root
            mode=0644
            backup=yes
  notify:
   - restart logstash
  tags:
   - logstash_conf

- name: Copy Logstash Input Configuration
  template: src=input.conf
            dest={{ logstash_conf_dir }}input.conf
            owner=root 
            group=root 
            mode=0644
  notify:
   - restart logstash
  tags:
   - logstash_conf


- name: Copy Logstash Filter Configuration
  template: src=filters.conf
            dest={{ logstash_conf_dir }}filters.conf
            owner=root 
            group=root 
            mode=0644
  notify:
   - restart logstash
  tags:
   - logstash_conf


- name: Copy Logstash Output Configuration
  template: src=output.conf
            dest={{ logstash_conf_dir }}output.conf
            owner=root 
            group=root 
            mode=0644
  notify:
   - restart logstash
  tags:
   - logstash_conf
