- name: Download Java
  command: "wget -q -O {{java_package}} --no-check-certificate --no-cookies --header 'Cookie:oraclelicense=accept-securebackup-cookie' {{download_url}} creates={{java_package}}"

- name: Remove openJdk if exists
  yum: name=java-1.7.0-openjdk state=absent
  
- name: install oracle java rpm
  yum: name={{ java_package }} state=present

- name: Make Java available for system
  command: 'alternatives --install "/usr/bin/java" "java" "/usr/java/default/bin/java" 2000'
