- name: Install nrpe and nagios plugins
  yum: pkg={{item}} state=installed
  with_items:
    - nrpe
    - nagios-plugins-all
    - check_nrpe

- name: copy nrpe.cfg
  template:
    src=nrpe.cfg
    dest=/etc/nagios/nrpe.cfg
    owner=root
    group=root
    mode=0644
  notify: restart nagios-nrpe-server 

- name: Ensure NRPE server is running
  service: name="nrpe" state=restarted enabled=yes

- name: Read iptable rules
  shell: iptables -L
  register: iptablesrules
  tags: iptables

- name: Allow nagios nrpe port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 5666 -j ACCEPT -m comment --comment "NagiosNRPE"
  when: iptablesrules.stdout.find("NagiosNRPE") == -1
  tags: iptables

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables
  sudo: yes
  tags: iptables

- name: create entry for failed events check in nrpe.cfg file at datasense server
  lineinfile: dest=/etc/nagios/nrpe.cfg line='{{ datasense_nrpe_failed_events_cmd }} -u {{ datasense_mysql_monitoring_user }} -p {{ datasense_mysql_monitoring_pass }}'
  when: "'datasense' in group_names"

- name: create entry for failed events check in nrpe.cfg file at freeshr update server
  lineinfile: dest=/etc/nagios/nrpe.cfg line='{{ freeshr_update_nrpe_failed_events_cmd }} -u {{ freeshr_update_mysql_monitoring_user }} -p {{ freeshr_update_mysql_monitoring_pass }}'
  when: "'freeshr-update-server' in group_names"