---
- name: install haproxy
  yum: name={{ item }} state=latest
  with_items:
    - haproxy

- name: define proxy config
  template: 
      src=haproxy.j2
      dest=/etc/haproxy/haproxy.cfg
      mode=644
      owner=haproxy
      group=haproxy

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules

- name: Allow listen access to haproxy
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 80 -j ACCEPT -m comment --comment "HAPROXY"
  when: iptablesrules.stdout.find("HAPROXY") == -1

- name: save iptables
  command: service iptables save

- name: copy rsyslog configuration
  template:
    src=haproxy.rsyslog.j2
    dest=/etc/rsyslog.d/haproxy.conf

- name: enable rsyslog udp server
  lineinfile:
    dest=/etc/rsyslog.cfg
    line='$ModLoad imudp'
    state=present

- name: rsyslog udp server configuration
  lineinfile:
    dest=/etc/rsyslog.cfg
    line='$UDPServerRun 514'
    state=present

- name: rsyslog udp allow only localhost
  lineinfile:
    dest=/etc/rsyslog.cfg
    line='$UDPServerAddress 127.0.0.1'
    insertafter='^\$UDPServerRun'
    state=present

- service: name=rsyslog state=restarted
  
- service: name=haproxy state=restarted enabled=yes

