---
- name: install haproxy
  yum: name={{ item }} state=latest
  with_items:
    - haproxy

- name: define proxy config
  template: 
      src=haproxy.j2 
      dest=/etc/haproxy/haproxy.cfg 
      mode=644
      owner=haproxy
      group=haproxy

- service: name=haproxy state=restarted enabled=yes