- hosts: all:!external-registries
  become_user: root
  become: yes
  roles:
    - shr-base
    - { role: ssh-user, ssh_user: bdshr }
    - { role: selinux, selinux_state: permissive, selinux_policy: targeted }
  tags:
    - setup

- hosts: haproxy
  become_user: root
  become: yes
  roles:
    - haproxy
  tags:
    - haproxy

- hosts: identity-server
  become_user: root
  become: yes
  roles:
    - identity-server
  tags:
    - identity-server

