- hosts: datasense
  gather_facts: false
  become_user: root
  become: yes
  roles:
    - datasense-server
  tags:
    - datasense

- hosts: patient-journal
  become_user: root
  become: yes
  roles:
    - patient-journal
  tags:
    - patient-journal