- hosts: dhis
  sudo: yes
  user: user
  vars:
    dhis_home: /home/dhis/
    admin_username: admin
    admin_password: 0f359740bd1cda994f8b55330c86d845
    http_port: 8080
    https_port: 8443
    tomcat_ver: 7.0.53

  roles:
     - tomcat
     - dhis