- name: "Install Cassandra"
  hosts: cassandra_node
  become_user: root
  become: yes
  roles:
    - cassandra-cluster
    - cassandra-repair-job
  tags:
    - cassandra
    
- name: "Setup Cassandra users"
  hosts: cassandra_seed_node
  become_user: root
  become: yes
  roles:
     - cassandra-user-setup
  run_once: true
  tags:
    - cassandra
    - cassandra-user-setup