---

- hosts: mci-ui
  sudo: true
  roles:
    - { role: apache, tags: ['infrastructure'] }
    - { role: php-packages, tags: ['infrastructure'] }
    - { role: mci-ui, tags: ['application'] }
  vars:
    mci_ui_home: "/var/www/mci_ui"