- name: Set up keyspace and users for health id server.
  hosts: cassandra_seed_node
  become_user: root
  become: yes
  roles:
  - { role: cassandra-keyspace,
      cassandra_keyspace: "{{ hostvars[groups['healthid-server'][0]]['healthId_keyspace'] }}",
      cassandra_keyspace_user: "{{ hostvars[groups['healthid-server'][0]]['healthId_cassandra_user'] }}",
      cassandra_keyspace_pass: "{{ hostvars[groups['healthid-server'][0]]['healthId_cassandra_pass'] }}",
      cassandra_keyspace_replication_strategy: "{{ hostvars[groups['healthid-server'][0]]['healthId_cassandra_replication_strategy'] }}",
      cassandra_keyspace_replication_factor: "{{ hostvars[groups['healthid-server'][0]]['healthId_cassandra_replication_factor'] }}" }
  tags:
    - healthid-server

- hosts: healthid-server
  become_user: root
  become: yes
  roles:
    - healthid-server
  tags:
    - healthid-server

- name: Set up keyspace and users
  hosts: cassandra_seed_node
  become_user: root
  become: yes
  roles:
  - { role: cassandra-keyspace,
      cassandra_keyspace: "{{ hostvars[groups['mci-server'][0]]['mci_keyspace'] }}",
      cassandra_keyspace_user: "{{ hostvars[groups['mci-server'][0]]['mci_cassandra_user'] }}",
      cassandra_keyspace_pass: "{{ hostvars[groups['mci-server'][0]]['mci_cassandra_pass'] }}",
      cassandra_keyspace_replication_strategy: "{{ hostvars[groups['mci-server'][0]]['mci_cassandra_replication_strategy'] }}",
      cassandra_keyspace_replication_factor: "{{ hostvars[groups['mci-server'][0]]['mci_cassandra_replication_factor'] }}" }
  tags:
    - mci-server

- name: Install MCI
  hosts: mci-server
  become_user: root
  become: yes
  roles:
    - mci-server
  tags:
    - mci-server

- name: Install MCI-LR
  hosts: mci-lr
  become_user: root
  become: yes
  roles:
    - mci-lr
  tags:
    - mci-lr

- name: Install MCI FHIR
  hosts: mci-fhir
  become_user: root
  become: yes
  roles:
    - mci-fhir
  tags:
    - mci-fhir

- name: Install MCI UI
  hosts: mci-ui
  become_user: root
  become: yes
  roles:
    - role: mci-ui
  vars:
    mci_ui_home: "/var/www/mci_ui"
  tags:
    - mci-ui

- name: "Install MCI-Background-Jobs"
  hosts: mci-background-jobs
  become_user: root
  become: yes
  roles:
    - mci-background-jobs
  tags:
    - mci-background-jobs