---

- hosts: nagios_host
  sudo: True
  vars_files:
    - vars/nagios.yml
    - group_vars/all
  roles:
   - role: nagios

  tags:
    - nagios-server

- hosts: nagios_agent
  sudo: True
  vars_files:
    - vars/nrpe.yml
  roles:
   - role: nagios-agent
  tags:
    - nagios-agents
