- name: "Add SHR Cassandra User"
  hosts: cassandra_seed_node
  become_user: root
  become: yes
  roles:
    -  { role: cassandra-keyspace, cassandra_keyspace: "{{ hostvars[groups['shr-server'][0]]['shr_keyspace'] }}",
        cassandra_keyspace_user: "{{ hostvars[groups['shr-server'][0]]['shr_cassandra_user'] }}",
        cassandra_keyspace_pass: "{{ hostvars[groups['shr-server'][0]]['shr_cassandra_pass'] }}",
        cassandra_keyspace_replication_strategy: "{{ hostvars[groups['shr-server'][0]]['shr_cassandra_replication_strategy'] }}",
        cassandra_keyspace_replication_factor: "{{ hostvars[groups['shr-server'][0]]['shr_cassandra_replication_factor'] }}" }
  tags:
    - shr-dstu2
    - shr

- name: "Install FreeSHR DSTU2"
  hosts: shr-server-dstu2
  become_user: root
  become: yes
  roles:
    - shr-server
  tags:
    - shr-dstu2
  vars:
    is_latest_shr: false

- name: "Install FreeSHR"
  hosts: shr-server
  become_user: root
  become: yes
  roles:
    - shr-server
  tags:
    - shr
  vars:
    shr_version: v2
    fhir_document_schema_version: v3

- name: "Install FreeSHR-Update-Server"
  hosts: freeshr-update-server
  become_user: root
  become: yes
  roles:
    - freeshr-update
  tags:
    - freeshr-update-server

- name: "Install SHR migration service"
  hosts: shr-migration-service
  become_user: root
  become: yes
  roles:
    - shr-migration-service
  tags:
    - shr-migration-service
