- hosts: tr-server
  become_user: root
  become: yes
  roles:
    - tr-server
  tags:
    - tr-server

- hosts: tr-server
  become_user: root
  become: yes
  roles:
    - tr-feed-server
  tags:
    - tr-feed-server

- hosts: tr-server
  become_user: root
  become: yes
  vars:
    sql_file: "concept_data.sql"
    database: "terminologies"
    data_destination_dir: "{{ tr_seed_data_dest_dir }}"
    mysql_user: "terminologies"
    mysql_password: "{{ tr_mysql_user_password }}"
    mysql_host: "127.0.0.1"
  roles:
    - mysql-data-dump
  tags:
    - tr-seed-data