- hosts: tr-server
  sudo: yes
  roles:
   - role: tr-server
  tags:
    - tr-server

- hosts: tr-server
  sudo: yes
  roles:
   - role: tr-feed-server
  tags:
    - tr-feed-server
     
- hosts: tr-server
  sudo: yes
  vars:
    sql_file: "concept_data.sql"
    database: "terminologies"
    data_destination_dir: "{{ tr_seed_data_dest_dir }}"
    mysql_user: "terminologies"
    mysql_password: "{{ tr_mysql_user_password }}"
  roles:
   - role: mysql-data-dump
  tags:
    - tr-seed-data