- hosts: tr-server
  become_user: root
  become: yes
  vars_files:
    - vars/all.txt
  roles:
    - tr-server
  tags:
    - tr-server

- hosts: tr-server
  become_user: root
  become: yes
  roles:
   - role: tr-feed-server
  tags:
    - tr-feed-server