- name : download go server rpm
  command: "wget -q -O /tmp/go-server-{{ go_server_version}}.noarch.rpm --no-check-certificate --no-cookies https://download.go.cd/binaries/{{ go_server_version }}/rpm/go-server-{{ go_server_version }}.noarch.rpm"

- name: install go server
  yum: name=/tmp/go-server-{{ go_server_version}}.noarch.rpm state=present

- name: create go user
  command: "htpasswd -sbn {{ go_server_admin }} {{ go_server_admin_password }}"
  register: passfile_contents
  tags:
    - go-user

- name: save go user
  lineinfile:
    line='{{ passfile_contents.stdout }}'
    dest=/var/go/htpasswd
    create=yes
    owner=go
    group=go
    mode=0640
  tags:
    - go-user

- name: start go server
  service: name=go-server enabled=yes state=started
  tags:
    - go-user

- name: Allow Go server port through firewall
  iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=8153 match=comment comment="GO Server"

- name: Allow Go Server SSL port through firewall
  iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=8154 match=comment comment="GO Server SSL"

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables