- name : download go server rpm
  get_url:
    url=http://download.go.cd/gocd-rpm/go-server-{{ go_server_version }}.noarch.rpm
    dest=/tmp/go-server-{{ go_server_version}}.noarch.rpm

- name: install go server
  yum: name=/tmp/go-server-{{ go_server_version}}.noarch.rpm state=present

- name: copy go config
  template:
    src=go-config.j2
    dest=/etc/go/cruise-config.xml
    backup=yes
    owner=go
    group=go
    mode=0644

- name: create go user
  command: "htpasswd -sbn {{ go_server_admin }} {{ go_server_admin_password }}"
  register: passfile_contents
  tags:
    - go-user

- name: save go user
  lineinfile:
    line='{{ passfile_contents.stdout }}'
    dest=/var/go/htpasswd
    create=yes
    owner=go
    group=go
    mode=0644
  tags:
    - go-user
    
- name: start go server
  service: name=go-server enabled=yes state=started
  tags:
    - go-user
  
