
- name: Install datastax repo
  copy:
    src=datastax.repo
    dest=/etc/yum.repos.d/datastax.repo
    owner=root group=root mode=0644

- name: Install opscenter
  yum: name=opscenter-free state=present

- name: Register iptable rules
  shell: iptables -L
  register: iptablesrules

- name: Allow Opscenter web
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8888 -j ACCEPT -m comment --comment "OpsCenter"
  when: iptablesrules.stdout.find("OpsCenter") == -1

- name: Allow Opscenter listener
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 61620 -j ACCEPT -m comment --comment "OpscenterListener"
  when: iptablesrules.stdout.find("OpscenterListener") == -1

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables

- name: Start opscenter
  service: name=opscenterd state=started
