---

- name: Ensure tmp directory exists
  file: dest=/tmp state=directory

- name: Copy RPM
  copy: src='{{ item }}' dest=/tmp/bdshr-terminology-server.rpm owner=root mode=777
  with_fileglob:
    - "{{rpm}}"

- name: Uninstall previous terminology server
  sudo: True
  yum: name=bdshr-terminology-server state=removed

- name: Install terminology server
  sudo: True
  yum: name=/tmp/bdshr-terminology-server.rpm state=present


- name: Allow app dir access to run user
  file:
    path={{ tr_server_install_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes
    recurse=yes
    state=directory

- name: Allow log dir access to run user
  file:
    path={{ tr_server_install_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes
    recurse=yes
    state=directory

- name: Permissions to tr server config
  file:
    path=/etc/bdshr-terminology-server
    src={{ tr_server_install_dir }}/etc
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link

- name: Permissions to service bdshr
  file:
    path=/etc/init.d/bdshr-terminology-server
    src={{ tr_server_install_dir }}/bin/bdshr-terminology-server
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link


- name: Permissions to var run
  file:
    path=/var/run/bdshr-terminology-server
    src={{ tr_server_install_dir }}/run
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link

- name: Restart terminology-server
  service: name=bdshr-terminology-server state=restarted enabled=yes

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules
  sudo: true

- name: Allow terminology server port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ tr_server_port }} -j ACCEPT -m comment --comment "TerminologyServer"
  sudo: true
  when: iptablesrules.stdout.find("TerminologyServer") == -1

- name: save iptables
  command: service iptables save
  sudo: true

- include: migrations.yml
