---
- name: Create mysql user
  mysql_user:
    login_user=root
    login_password={{ mysql_root_password }}
    name=terminologies
    password={{ tr_mysql_user_password }}
    priv=*.*:ALL,GRANT
    state=present

- name: Create Terminology database
  mysql_db: name=terminologies state=present login_user=terminologies login_password={{ tr_mysql_user_password }}

#- name: Copy database migrations
#  copy: src=chunking_history.sql.bz2 dest=/tmp/chunking_history.sql.bz2

- name: Ensure tmp directory exists
  file: dest=/tmp state=directory

- name: Copy RPM
  copy: src='{{ rpm }}' dest=/tmp/bdshr-terminology-server.rpm owner=root mode=777

- name: Uninstall previous terminology server
  sudo: True
  yum: name=bdshr-terminology-server state=removed

- name: Install terminology server
  sudo: True
  yum: name=/tmp/bdshr-terminology-server.rpm state=present

- name: copy tr server configuration
  template:
    src=bdshr-terminology-server.conf
    dest={{ tr_config_location }}
    mode=644
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}

- name: copy tr server openrms configuration
  template:
    src=openmrs-runtime.properties
    dest={{ tr_openmrs_runtime_properties_location }}
    mode=644
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}

  
- name: Allow app dir access to run user
  file:
    path={{ tr_server_install_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes
    recurse=yes
    state=directory

- name: Allow log dir access to run user
  file:
    path={{ tr_server_install_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes
    recurse=yes
    state=directory

- name: Permissions to tr server config
  file:
    path=/etc/bdshr-terminology-server
    src={{ tr_server_install_dir }}/etc
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link

- name: Permissions to service bdshr
  file:
    path=/etc/init.d/bdshr-terminology-server
    src={{ tr_server_install_dir }}/bin/bdshr-terminology-server
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link


- name: Permissions to var run
  file:
    path=/var/run/bdshr-terminology-server
    src={{ tr_server_install_dir }}/run
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link

- name: link openmrs to var run
  file:
    path=/var/run/bdshr-terminology-server/openmrs
    src={{ tr_server_install_dir }}/openmrs
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link

- name: create home .openmrs
  file:
    path=/home/{{ sharedhealth_user }}/.OpenMRS
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=directory

- name: link modules  home .openmrs
  file:
    path=/home/{{ sharedhealth_user }}/.OpenMRS/modules
    src={{ tr_server_install_dir }}/modules
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link
    
- name: Restart terminology-server
  service: name=bdshr-terminology-server state=restarted enabled=yes

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules
  sudo: true

- name: Allow terminology server port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ tr_server_port }} -j ACCEPT -m comment --comment "TerminologyServer"
  sudo: true
  when: iptablesrules.stdout.find("TerminologyServer") == -1

- name: save iptables
  command: service iptables save
  sudo: true

#- include: migrations.yml
