---

- name: Install open jdk
  yum: name=java-1.7.0-openjdk-devel state=latest

- name: Ensure tmp directory exists
  file: dest=/tmp state=directory

- name: Copy RPM
  copy: src='{{ item }}' dest=/tmp/bdshr-terminology-server.rpm owner=root mode=777
  with_fileglob:
    - "{{rpm}}"

- name: Uninstall previous terminology server
  sudo: True
  yum: name=bdshr-terminology-server state=removed

- name: Install RPM
  sudo: True
  yum: name=/tmp/bdshr-terminology-server.rpm state=present

- name: Start terminology-server
  service: name=bdshr-terminology-server state=restarted

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules
  sudo: true

- name: Allow terminology server port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 9080 -j ACCEPT -m comment --comment "TerminologyServer"
  sudo: true
  when: iptablesrules.stdout.find("TerminologyServer") == -1

- name: save iptables
  command: service iptables save
  sudo: true

- include: migrations.yml
