---
- name: Clean existing rpm
  file: path=/tmp/bdshr-terminology-server.rpm state=absent

- name: Create mysql user
  mysql_user:
    login_user=root
    login_password={{ mysql_root_password }}
    name=terminologies
    password={{ tr_mysql_user_password }}
    priv=*.*:ALL,GRANT
    state=present

- name: Create Terminology database
  mysql_db: name=terminologies state=present login_user=terminologies login_password={{ tr_mysql_user_password }}

- name: Copy RPM
  copy: src='{{ rpm }}' dest=/tmp/bdshr-terminology-server.rpm owner=root mode=777

- name: Uninstall previous terminology server
  yum: name=bdshr-terminology-server state=removed

- name: Install terminology server
  yum: name=/tmp/bdshr-terminology-server.rpm state=present

- name: copy tr server configuration
  template:
    src=bdshr-terminology-server.conf
    dest={{ tr_config_location }}
    mode=0640
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}

- name: copy tr server openrms configuration
  template:
    src=openmrs-runtime.properties
    dest={{ tr_openmrs_runtime_properties_location }}
    mode=0640
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
  
- name: Allow app dir access to run user
  file:
    path={{ tr_server_install_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    mode=0750
    follow=yes
    recurse=yes
    state=directory

- name: Allow log dir access to run user
  file:
    path={{ tr_server_install_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    mode=0750
    follow=yes
    recurse=yes
    state=directory

- name: Permissions to tr server config
  file:
    path=/etc/bdshr-terminology-server
    src={{ tr_server_install_dir }}/etc
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    mode=0750
    state=link

- name: Permissions to service bdshr
  file:
    path=/etc/init.d/bdshr-terminology-server
    src={{ tr_server_install_dir }}/bin/bdshr-terminology-server
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    mode=0755
    state=link

- name: Permissions to var run
  file:
    path=/var/run/bdshr-terminology-server
    src={{ tr_server_install_dir }}/run
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    mode=0750
    state=link

- name: link openmrs to var run
  file:
    path=/var/run/bdshr-terminology-server/openmrs
    src={{ tr_server_install_dir }}/openmrs
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    mode=0750
    state=link

- name: create home .openmrs
  file:
    path=/home/{{ sharedhealth_user }}/.OpenMRS
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=directory
    mode=0750

- name: link modules  home .openmrs
  file:
    path=/home/{{ sharedhealth_user }}/.OpenMRS/modules
    src={{ tr_server_install_dir }}/modules
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    mode=0750
    state=link

- name: Copy atom feed omod
  copy:
    src='{{ item }}'
    dest={{ tr_server_install_dir }}/modules/
    mode=0750
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
  with_fileglob:
    - "{{atomfeedomod}}"

- name: Copy Rest services
  copy:
    src='{{ item }}'
    dest={{ tr_server_install_dir}}/modules/
    mode=0750
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
  with_fileglob:
    - "{{restomod}}"

- name: Restart terminology-server
  service: name=bdshr-terminology-server state=restarted enabled=yes

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules

- name: Allow terminology server port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ tr_server_port }} -j ACCEPT -m comment --comment "TerminologyServer"
  when: iptablesrules.stdout.find("TerminologyServer") == -1

- name: save iptables
  command: service iptables save
