---
- name: Copy mysql driver
  copy: src='mysql-connector-java-5.0.8-bin.jar' dest=/tmp mode=755

- name: Copy migrations
  template: src=migrations.j2 dest=/tmp/migrations.xml mode=755

- name: Copy httplib2
  copy: src=httplib2-0.8 dest=/tmp mode=755

- name: Install httplib2
  command: python setup.py install chdir=/tmp/httplib2-0.8

- name: Wait for tr server to start
  uri: url=http://localhost:{{ tr_server_port }}/openmrs/index.htm timeout=300 return_content=true

- name: Check whether liquibase is installed already
  yum: name=liquibase state=present
  
- name: Clear checksums
  shell: liquibase --url="jdbc:mysql://localhost:3306/terminologies" --username=root --password=password --changeLogFile=/tmp/migrations.xml --classpath=/tmp/mysql-connector-java-5.0.8-bin.jar --logLevel=debug clearCheckSums

- name: Apply migrations
  shell: liquibase --url="jdbc:mysql://localhost:3306/terminologies" --username=root --password=password --changeLogFile=/tmp/migrations.xml --classpath=/tmp/mysql-connector-java-5.0.8-bin.jar --logLevel=debug update
