---
- name: Clean existing
  shell: rm -f /tmp/patient-journal.rpm
  sudo: true

- name: Copy rpm
  copy: src=/tmp/patient-journal-0.1-1.noarch.rpm dest=/tmp/patient-journal.rpm mode=755

- name: Remove patient-journal
  yum: name=patient-journal-0.1-1.noarch state=absent
  sudo: true

- name: Install patient-journal
  yum: name=/tmp/patient-journal.rpm state=present
  sudo: true

- name: Allow app dir access to run user
  file:
    path={{ patient_journal_install_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes
    recurse=yes
    state=directory


- name: Allow log dir access to run user
  file:
    path={{ patient_journal_log_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes
    recurse=yes
    state=directory
  
- name: Copy patient-journal properties
  template: src=patient-journal
    dest=/etc/default/patient-journal
    mode=755
    owner={{ sharedhealth_user}}
    group={{ sharedhealth_group}}

- name: Permissions to service patient-journal
  file:
    path=/etc/init.d/patient-journal
    src={{ patient_journal_install_dir }}/bin/patient-journal
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link


- name: Permissions to var run
  file:
    path=/var/run/patient-journal
    src={{ patient_journal_install_dir }}/var
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules

  sudo: true
- name: Allow bdshr port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ patient_journal_port }} -j ACCEPT -m comment --comment "PATIENT-JOURNAL"
  sudo: true
  when: iptablesrules.stdout.find("PATIENT-JOURNAL") == -1

- name: save iptables
  command: service iptables save
  sudo: true

- name: Restart patient-journal
  service: name=patient-journal state=restarted enabled=yes
  tags: run_patient_journal
