---
# tasks file for iptables

- name: start iptables
  service: name=iptables state=started enabled=yes

- name: Allow localhost interface
  iptables: chain=INPUT in_interface=lo jump=ACCEPT match=comment comment=lo

- name:  Allow Established
  iptables: chain=INPUT jump=ACCEPT match=state ctstate=ESTABLISHED,RELATED comment=APACHE2
  when: iptablesrules.stdout.find("ESTABLISHED") == -1

- name: Allow SSH
  iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=22 match=comment comment=SSH
  when: iptablesrules.stdout.find("SSH") == -1

- name: DROP ALL Incoming connections except those which are marked as ACCEPT
  iptables: chain=INPUT policy=DROP

- name: DROP all Forwards
  iptables: chain=FORWARD policy=DROP

- name: Allow all output
  iptables: chain=OUTPUT policy=ACCEPT

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables