---
- name: Clean existing rpm
  shell: rm -f /tmp/bdshr.rpm
  sudo: true

- name: Clean existing rpm
  shell: rm -f /tmp/shrid.rpm
  sudo: true
  
- name: copy keystore
  copy: src=shrid.cer dest=/tmp/shrid.cer
  sudo: true
  
- name: install identity server certificate to java keystore
  shell: keytool -import -keystore {{ ansible_env.JAVA_HOME | default('/usr/java/default') }}/lib/security/cacerts -alias shrid -file /tmp/shrid.cer -storepass changeit -noprompt
  sudo: true
  ignore_errors: true
  
- name: Copy rpm
  copy: src=/tmp/shr-0.1-1.noarch.rpm dest=/tmp/bdshr.rpm mode=755

- name: Remove bdshr
  yum: name=shr-0.1-1.noarch state=absent
  sudo: true

- name: Install bdshr
  yum: name=/tmp/bdshr.rpm state=present
  sudo: true

- name: Copy SHR properties
  copy: src={{deployment_environment}}-bdshr
    dest=/etc/default/bdshr
    mode=755

- name: Restart bdshr
  service: name=bdshr state=restarted
  sudo: true

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules

  sudo: true
- name: Allow bdshr port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8081 -j ACCEPT -m comment --comment "BDSHR"
  sudo: true
  when: iptablesrules.stdout.find("BDSHR") == -1

- name: save iptables
  command: service iptables save
  sudo: true
