---
- name: Disable nagios notifications for host
  nagios: action=disable_alerts host={{ inventory_hostname }} services=shr_proc,shr_http
  delegate_to: "{{ item }}"
  with_items: groups['nagios-hosts']

- name: Clean existing rpm
  shell: rm -f /tmp/bdshr.rpm

- name: Copy rpm
  copy: src={{ rpm }} dest=/tmp/bdshr.rpm mode=755

- name: Remove bdshr
  yum: name=shr.noarch state=absent

- name: Install bdshr
  yum: name=/tmp/bdshr.rpm state=present

- name: Allow app dir access to run user
  file:
    path={{ bdshr_install_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes
    recurse=yes
    state=directory


- name: Allow log dir access to run user
  file:
    path={{ bdshr_log_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes
    recurse=yes
    state=directory
    
- name: Copy SHR properties
  template:
    src=bdshr.j2 
    dest=/etc/default/bdshr
    mode=644
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}


- name: Permissions to service bdshr
  file:
    path=/etc/init.d/bdshr
    src={{ bdshr_install_dir }}/bin/bdshr
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link


- name: Permissions to var run
  file:
    path=/var/run/bdshr
    src={{ bdshr_install_dir }}/var
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link

- name: Apply migrations to leader node
  shell: "{{ bdshr_install_dir }}/bin/migrate.sh"
  when: run_migrations == "yes"
  
- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules

- name: Allow bdshr port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ bdshr_port }} -j ACCEPT -m comment --comment "BDSHR"
  when: iptablesrules.stdout.find("BDSHR") == -1

- name: save iptables
  command: service iptables save

- name: Start bdshr
  service: name=bdshr state=restarted enabled=yes
  tags: run_bdshr

- name: Enable nagios notifications for host
  nagios: action=enable_alerts host={{ inventory_hostname }} services=shr_proc,shr_http
  delegate_to: "{{ item }}"
  with_items: groups['nagios-server']
