dependencies:
  - { role: oracle-java }
  - { role: sharedhealth-user }
  - { role: mysql, local_mysql_username: {{ datasense_mysql_user }}, local_mysql_password: {{ datasense_mysql_password }} }
  - { role: host-entries, exclude: "none" }
