- name: copy cassandra user credentials change script
  template:
    src=cassandra_users.cql dest=/tmp/cassandra_users.cql
    mode=0644

- name: execute change cassandra user credentials script
  shell: "cqlsh {{ inventory_hostname }} -u cassandra -p {{ cassandra_old_admin_pass }} -f /tmp/cassandra_users.cql"
  register: command_result
  failed_when: "'Connection error' in command_result.stderr"
  no_log: True