- name: Install datastax repo
  copy:
    src=datastax.repo
    dest=/etc/yum.repos.d/datastax.repo
    owner=root group=root mode=0644

- name: Install cassandra
  yum: name=dsc20 state=present

- name: Downlaod jna
  get_url:
    url={{ cassandra_jna_download_url }}
    dest=/usr/share/cassandra/lib/jna.jar
    owner=cassandra group=cassandra mode=0755

- name: Update security conf for jna
  lineinfile:
    dest: /etc/security/limits.conf
    line: "{{ item.line }}"
  with_items:
    - { line: "* - memlock unlimited" }
    - { line: "* - nofile 100000" }
    - { line: "* - nproc 32768" }
    - { line: "* - as unlimited" }

- name: Allow cassandra rpc port through firewall
  iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=9160 match=comment comment=CassandraRpc

- name: Allow Cassandra inter-node cluster communication
  iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=7000 match=comment comment=CassandraInterNode

- name: Allow Cassandra JMX monitoring
  iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=7199 match=comment comment=CassandraJMX

- name: Allow Cassandra cql native transport
  iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=9042 match=comment comment=CassandraNative

- name: Allow Opscenter monitoring
  iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=61620 match=comment comment=OpscenterMonitoring
  when:
    - groups['opscenter_server'] is defined and groups['opscenter_server'] > 0

- name: Allow Opscenter agents
  iptables: chain=INPUT jump=ACCEPT protocol=tcp destination_port=61621 comment=OpscenterAgents
  when:
    - groups['opscenter_server'] is defined and groups['opscenter_server'] > 0

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables

- name: stop cassandra
  service: name=cassandra state=stopped

# doing this deletes all data in the system. We should do this only if a default cluster is already setup.
#- name: delete system data
#  command: rm -rf /var/lib/cassandra/data/system/*

- name: copy config
  template: src=cassandra.yaml dest=/etc/cassandra/conf/

- name: allow cassandra user to write to commitlog
  file:
    path={{ cassandra_commit_log_dir }}
    owner=cassandra
    group=cassandra
    follow=yes
    recurse=yes
    state=directory

 # - name: set hostname/ip for JMX
 #   lineinfile: dest=/etc/cassandra/conf/cassandra-env.sh regexp='hostname' line='JVM_OPTS="$JVM_OPTS -Djava.rmi.server.hostname={{ inventory_hostname }}"' backup=yes

- name: install system monitoring tools
  yum: name={{ item }} state=present
  with_items:
    - dstat

- name: start cassandra
  service: name=cassandra state=started enabled=yes

- name: Pause for Cassandra to start up
  pause: seconds=60