---
- name: Clean existing
  shell: rm -f /tmp/datasense.rpm /tmp/dhis_config.zip
  sudo: true

- name: Clean existing dhis_config folder
  shell: rm -rf /opt/datasense/lib/dhis_config
  sudo: true

- name: Copy rpm
  sudo: true
  copy: src={{ rpm }} dest=/tmp/datasense.rpm mode=755

- name: Install MySQL
  yum: name={{ item }} state=present
  sudo: true
  with_items:
    - MySQL-python
    - mysql
    - mysql-server

- name: Create Datasense datasense
  mysql_db: name=datasense state=present login_user=root login_password=password
  sudo: true

- name: Check for existing installations
  shell: rpm -q datasense-0.1-1
  register: datasense_installed
  ignore_errors: yes
  sudo: true

- name: Remove existing installation if any
  shell: yum remove -y datasense-0.1-1
  when: datasense_installed.rc == 0
  sudo: true

- name: Install datasense
  shell: yum install -y /tmp/datasense.rpm
  sudo: true

- name: Copy Datasense properties
  copy: src={{deployment_environment}}-datasense
    dest=/etc/default/datasense
    mode=755

- name: Unzip dhis_config
  unarchive: src={{ dhis_config_zip }} dest=/opt/datasense/lib

- name: Start datasense
  service: name=datasense state=restarted
  sudo: true

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules
  sudo: true

- name: Allow datasense port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8082 -j ACCEPT -m comment --comment "datasense"
  sudo: true
  when: iptablesrules.stdout.find("datasense") == -1

- name: save iptables
  command: service iptables save
  sudo: true
