---
- name: Clean existing
  shell: rm -f /tmp/datasense.rpm /tmp/dhis_config.zip

- name: Copy rpm
  copy: src={{ rpm }} dest=/tmp/datasense.rpm mode=755

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules


- name: Allow datasense port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ datasense_port }} -j ACCEPT -m comment --comment "datasense"
  when: iptablesrules.stdout.find("datasense") == -1

- name: save iptables
  command: service iptables save
  when: iptablesrules.stdout.find("datasense") == -1
  
- name: Install MySQL
  yum: name={{ item }} state=present
  with_items:
    - MySQL-python
    - mysql
    - mysql-server

- name: Create Datasense datasense
  mysql_db: name=datasense state=present login_user=root login_password=password

- name: Remove existing installations if any
  yum: name=datasense-0.1-1 state=absent

- name: Clean existing dhis_config folder
  shell: rm -rf {{ datasense_install_dir}}/lib/dhis_config
  
- name: Install datasense
  yum: name=/tmp/datasense.rpm state=present

- name: Allow app dir access to run user
  file:
    path={{ datasense_install_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes
    recurse=yes
    state=directory


- name: Allow log dir access to run user
  file:
    path={{ datasense_log_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes
    recurse=yes
    state=directory

- name: Copy Datasense properties
  template: src=datasense.j2
    dest=/etc/default/datasense
    mode=755
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}


- name: Unzip dhis_config
  unarchive:
    src={{ datasense_dhis_config_zip }}
    dest=/opt/datasense/lib
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes

- name: Allow dhis_config access to sharedhealth
  file:
    path={{ datasense_install_dir }}/lib/dhis_config
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes
    recurse=yes
    state=directory

- name: Permissions to service bdshr
  file:
    path=/etc/init.d/datasense
    src={{ datasense_install_dir }}/bin/datasense
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link


- name: Permissions to var run
  file:
    path=/var/run/datasense
    src={{ datasense_install_dir }}/var
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link

- name: Start datasense
  service: name=datasense state=restarted enabled=yes
  sudo_user : "{{ sharedhealth_user }}"
  tags: run_datasense

