---
- name: Clean existing
  shell: rm -f /tmp/identity-server.rpm
  sudo: true

- name: Copy rpm
  copy: src=/tmp/identity-server-0.1-1.noarch.rpm dest=/tmp/identity-server.rpm mode=755

- name: Remove identity-server
  yum: name=identity-server-0.1-1.noarch state=absent
  sudo: true

- name: Install identity-server
  yum: name=/tmp/identity-server.rpm state=present
  sudo: true

- name: copy java keystore
  copy: src=identityServer.jks dest={{ ansible_env.HOME | default('~') }}/identityServer.jks
  
- name: Copy identity-server properties
  copy: src={{deployment_environment}}-identity-server
    dest=/etc/default/identity-server
    mode=755

- name: Restart identity-server
  service: name=identity-server state=restarted
  sudo: true

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules

  sudo: true
- name: Allow bdshr port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8080 -j ACCEPT -m comment --comment "IDENTITY-SERVER"
  sudo: true
  when: iptablesrules.stdout.find("IDENTITY-SERVER") == -1

- name: save iptables
  command: service iptables save
  sudo: true
