---
- name: Delete terminology feed omod
  shell: rm -f {{ tr_server_install_dir}}/modules/freeshr-terminology-feed-*.omod
  sudo: yes

- name: Copy terminology feed omod
  copy:
    src='{{ item }}'
    dest={{ tr_server_install_dir}}/modules/
    mode=755
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
  with_fileglob:
    - "{{trfeedomod}}"

- name: Copy terminology server properties file
  template: src=tr-server.properties.j2
    dest={{ tr_server_install_dir}}/etc/tr-server.properties
    mode=755
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group}}

- name: Restart terminology-server
  service: name=bdshr-terminology-server state=restarted enabled=yes
