---

- name: Copy atom feed omod
  copy: src='{{ item }}' dest=/var/lib/bdshr-terminology-server/modules/ mode=755 owner=root
  with_fileglob:
    - "{{omod}}"

- name: Copy Rest services
  copy: src='{{ item }}' dest=/var/lib/bdshr-terminology-server/modules/ mode=755 owner=root
  with_fileglob:
    - "{{restomod}}"

- name: Copy terminology feed omod
  copy: src='{{ item }}' dest=/var/lib/bdshr-terminology-server/modules/ mode=755 owner=root
  with_fileglob:
    - "{{atomfeedomod}}"

- name: Ensure terminology server config directory exists
  file: dest={{config_home}} state=directory    

- name: Copy terminology server properties file
  copy: src={{deployment_environment}}-tr-server.properties 
    dest={{config_home}}/tr-server.properties 
    mode=755 owner=root    

- name: Stop tr
  command:
    service bdshr-terminology-server stop

- name: Start tr
  command:
    service bdshr-terminology-server start
