---
- name: Install MySQL
  yum: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql
    - MySQL-python

- name: Start Mysql Service
  action: service name=mysqld state=started enabled=true

- name: Update mysql root password
  command: /usr/bin/mysqladmin -u {{ local_mysql_username }} password {{ local_mysql_password }}
  ignore_errors: yes

- name: Create Terminology database
  mysql_db: name=terminologies state=present login_user={{ local_mysql_username }} login_password={{ local_mysql_password }}

- name: Copy database migrations
  copy: src=chunking_history.sql.bz2 dest=/tmp/chunking_history.sql.bz2
