---
- name: Check if any version of mysql is present
  command: mysql --version
  register: anyMysqlPresent
  ignore_errors: true

- name: Check mysql version if installed
  command: mysql --version
  register: mysqlVersion
  when: anyMysqlPresent | success

- name: Uninstall MySQL if 5.1 is present
  yum: name={{ item }} state=absent
  with_items:
    - mysql-server
    - mysql
    - MySQL-python
  when: anyMysqlPresent | success and mysqlVersion.stdout.find('5.1') != -1

- name: Install wget
  yum: name=wget state=present

- name: Check if RPM is present
  stat: path=mysql-community-release-el6-5.noarch.rpm
  register: mysqlRPM

- name: Download latest mysql RPM if not present
  command: wget http://repo.mysql.com/mysql-community-release-el6-5.noarch.rpm
  when: mysqlRPM.stat.exists == false

- name: Check if mysql RPM is installed
  command: rpm -qa | grep -i mysql-community
  register: installedRPM

- name: Install RPM if not installed previously
  command: rpm -Uvh mysql-community-release-el6-5.noarch.rpm
  when: installedRPM.stdout.find('mysql-community-release') == -1

- name: Check if MySql has survived Uninstallation
  command: mysql --version
  register: mysqlPresent
  ignore_errors: true

- name: Check if old mysql directory is present
  stat: path=/var/lib/mysql
  register: mysqlDir

- name: Delete old mysql files
  command: rm -rf /var/lib/mysql
  when: mysqlDir.stat.exists == true and mysqlPresent | failed

- name: Install MySQL
  yum: name={{ item }} state=present
  with_items:
    - mysql-server
    - mysql
    - MySQL-python

- name: Start Mysql Service
  action: service name=mysqld state=started enabled=true

- name: Update mysql root password
  command: /usr/bin/mysqladmin -u root password {{ mysql_root_password }}
  ignore_errors: yes

