---

- name: Create {{mci_ui_home}} dir
  file: path={{mci_ui_home}} state=directory

- name: Install current version
  unarchive: src='{{item}}' dest={{mci_ui_home}}
  sudo: true
  with_fileglob:
    - "{{dist}}"

- name: Copy Configuration
  copy:
    src=parameters.yml
    dest={{mci_ui_home}}/app/config/parameters.yml

- name:  Update MCI API Endpoint configuration
  lineinfile: dest={{mci_ui_home}}/app/config/parameters.yml
              regexp='^    api_end_point{{":"}} '
              insertafter='^    api_end_point{{":"}} '
              line='    api_end_point{{":"}} {{api_uri_prefix}}'
              state=present

- name:  Update Identity Server configuration
  lineinfile: dest={{mci_ui_home}}/app/config/parameters.yml
              regexp='^    identity_server_domain{{":"}} '
              insertafter='^    identity_server_domain{{":"}} '
              line='    identity_server_domain{{":"}} {{identity_server_domain}}'
              state=present

- name:  Update Identity Server Port configuration
  lineinfile: dest={{mci_ui_home}}/app/config/parameters.yml
              regexp='^    identity_server_port{{":"}} '
              insertafter='^    identity_server_port{{":"}} '
              line='    identity_server_port{{":"}} {{identity_server_port}}'
              state=present


- name: Re-Build Applicaiton
  shell: chdir={{mci_ui_home}} bin/deploy.sh
  notify: restart apache
  sudo: true

- name: Change owner to apache user
  shell: chown -R apache:apache {{mci_ui_home}}{{item}}
  with_items:
    - /app/cache
    - /app/logs
