---

- name: Create {{mci_ui_home}} dir
  file: path={{mci_ui_home}} state=directory

- name: Install current version
  unarchive: src='{{item}}' dest={{mci_ui_home}} owner=apache group=apache
  sudo: true
  with_fileglob:
    - "{{dist}}"

- name: Copy Configuration
  template: src=mci.j2
    dest={{mci_ui_home}}/app/config/parameters.yml

- name: Re-Build Applicaiton
  shell: chdir={{mci_ui_home}} bin/deploy.sh
  notify: restart apache
  sudo: true

- name: Change owner to apache user
  shell: chown -R apache:apache {{mci_ui_home}}