---

- name: Checkout MCI-UI code
  git: repo=https://github.com/SharedHealth/MCI-Admin.git
    dest={{mci_ui_home}}
    version={{version|default("HEAD")}}
    update=yes

- name: Copy Configuration
  copy:
    src=parameters.yml
    dest={{mci_ui_home}}/app/config/parameters.yml

- name:  Update configuration
  lineinfile: dest={{mci_ui_home}}/app/config/parameters.yml
              regexp='^    api_end_point{{":"}} '
              insertafter='^    api_end_point{{":"}} '
              line='    api_end_point{{":"}} {{api}}'
              state=present

- name: Download all dependencies Ignorring php intl
  shell: chdir={{mci_ui_home}} /usr/local/bin/composer require 'symfony/icu:1.0.*'

- name: Update dependencies
  shell: chdir={{mci_ui_home}} /usr/local/bin/composer update
  sudo: true

- name: Create assets link to web directory
  file: src={{mci_ui_home}}/app/Resources/assets dest={{mci_ui_home}}/web/assets state=link

- name: Install assets
  shell: chdir={{mci_ui_home}} app/console  assets:install --symlink --relative --env=prod
  sudo: true

- name: Dump assets
  shell: chdir={{mci_ui_home}} app/console  assetic:dump --env=prod
  sudo: true

- name: Clear cache
  shell: chdir={{mci_ui_home}} app/console  cache:clear --env=prod
  notify: restart apache
  sudo: true

- name: Make cache writable
  shell: chmod -R 0777 {{mci_ui_home}}{{item}}
  with_items:
    - /app/cache
    - /app/logs

- name: Change owner to apache user
  shell: chown -R apache:apache {{mci_ui_home}}{{item}}
  with_items:
    - /app/cache
    - /app/logs
