---
- name: Clean existing
  shell: rm -f /tmp/mci.rpm
  sudo: true

- name: Copy rpm
  copy: src='{{item}}' dest=/tmp/mci.rpm mode=755
  with_fileglob:
    - "{{rpm}}"

- name: Check for existing installations
  shell: rpm -q mci-0.1-1
  register: mci_installed
  ignore_errors: yes
  sudo: true

- name: Remove existing installation if any
  shell: yum remove -y mci-0.1-1
  when: mci_installed.rc == 0
  sudo: true

- name: Install mci
  shell: yum install -y /tmp/mci.rpm
  sudo: true
  notify: Start mci

- name: Start cassandra
  service: name=cassandra state=started
  sudo: true

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules
  sudo: true

- name: Allow mci port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8081 -j ACCEPT -m comment --comment "MCI"
  sudo: true
  when: iptablesrules.stdout.find("MCI") == -1

- name: save iptables
  command: service iptables save
  sudo: true
