---
- include: config-hostname.yml tags=config

- name: Install open jdk
  yum: name=java-1.7.0-openjdk-devel state=latest

- name: Start Cassandra
  service: name=cassandra state=started

- name: Ensure tmp directory exists
  file: dest=/tmp state=directory

- name: Copy RPM
  copy: src='{{ item }}' dest=/tmp/bdshr-mci-server.rpm mode=755 owner=root mode=777
  with_fileglob:
    - "{{rpm}}"

- name: Uninstall previous MCI server
  sudo: True
  yum: name=bdshr-mci-server state=removed

- name: Install RPM
  sudo: True
  yum: name=/tmp/bdshr-mci-server.rpm state=present

- name: Start MCI
  shell: service bdshr-mci-server start
  sudo: true

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules
  sudo: true

- name: Allow MciServer server port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 8081 -j ACCEPT -m comment --comment "MciServer"
  sudo: true
  when: iptablesrules.stdout.find("MciServer") == -1

- name: save iptables
  command: service iptables save
  sudo: true
