---

- name: Copy epel-release rpm
  copy: src=epel-release-6-8.noarch.rpm dest=/tmp/epel-release-6-8.noarch.rpm mode=755

- name: Install EPEL repo.
  yum:
    name: /tmp/epel-release-6-8.noarch.rpm
    state: present
  sudo: yes

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present

- name: Install libselinux-python
  yum: name=libselinux-python state=present



