---
- name: Check for pre-installed epel repo
  command: "yum repolist epel -C -e 0"
  register: check_epel

- name: Install EPEL repo.
  yum:
    name: "{{ epel_repo_url }}"
    state: present
  when: check_epel.stdout.find('epel') == -1

- name: Import EPEL GPG key.
  rpm_key:
    key: "{{ epel_repo_gpg_key_url }}"
    state: present
  when: check_epel.stdout.find('epel') == -1

- name: Install libselinux-python
  yum: name=libselinux-python state=present
