---

- name: Check if go server is already Installed
  command: rpm -q go-server
  register: rpm_check_go_server
  ignore_errors: True

- name: Install the go server
  action: command rpm -Uvh --replacepkgs http://download01.thoughtworks.com/go/13.4.1/ga/go-server-13.4.1-18342.noarch.rpm
  when: rpm_check_go_server.rc == 1

- name: Allow port through firewall
  action: command iptables -A INPUT -m tcp -p tcp --dport 8153 -j ACCEPT
  when: rpm_check_go_server.rc == 1

- name: Save firewall rules
  action: command service iptables save
  when: rpm_check_go_server.rc == 1

- name: Install ssh keys
  command: ssh-keygen -t rsa -N "" -f ~/id_rsa creates=~/.ssh/id_rsa.pub
  sudo: True
  sudo_user: "{{go_user}}"
- name: create .ssh directory
  file: path=~/.ssh state=directory
  sudo: True
  sudo_user: "{{go_user}}"
- name: move files into the directory
  command: mv ~/id_rsa.pub ~/id_rsa ~/.ssh/ creates=~/.ssh/id_rsa.pub
  sudo: True
  sudo_user: "{{go_user}}"
- name: set permissions
  command: chmod 700 -R ~/.ssh/
  sudo: True
  sudo_user: "{{go_user}}"
- name: set restrictive permissions to private key
  command: chmod 600 ~/.ssh/id_rsa
  sudo: True
  sudo_user: "{{go_user}}"
