---
- name: Copy rpm
  copy: src='{{ rpm }}' dest=/tmp/mci-fhir.rpm mode=0755

- name: Remove existing installation if any
  yum: name=mci-fhir.noarch state=absent

- name: Install mci-fhir
  yum: name=/tmp/mci-fhir.rpm state=present

- name: Allow app dir access to run user
  file:
    path={{ mci_fhir_install_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes
    recurse=yes
    state=directory
    mode=0750


- name: Allow log dir access to run user
  file:
    path={{ mci_fhir_log_dir }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    follow=yes
    recurse=yes
    state=directory
    mode=0750

- name: Copy properties
  template: src=mci-fhir.j2
    dest=/etc/default/mci-fhir
    mode=0750
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}

- name: Copy profiles
  copy:
   src=profiles/
   dest={{ mci_fhir_profiles_folder }}
   mode=0750
   owner={{ sharedhealth_user }}
   group={{ sharedhealth_group }}

- name: Permissions to service mci-fhir
  file:
    path=/etc/init.d/mci-fhir
    src={{ mci_fhir_install_dir }}/bin/mci-fhir
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link
    mode=0755

- name: Create health id file directory path
  file:
    path={{ mci_health_id_file_directory_path }}
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    mode=0750
    follow=yes
    recurse=yes
    state=directory

- name: Create health id file
  file:
    path={{mci_health_id_file_directory_path}}/{{mci_fhir_idp_client_id}}-available_hids.txt
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    mode=0640
    follow=yes
    state=touch

- name: Permissions to var run
  file:
    path=/var/run/mci-fhir
    src={{ mci_fhir_install_dir }}/var
    owner={{ sharedhealth_user }}
    group={{ sharedhealth_group }}
    state=link
    mode=0750

- name: Get IpTable rules
  shell: iptables -L
  register: iptablesrules

- name: Allow mci-fhir port through firewall
  command: /sbin/iptables -I INPUT 1 -p tcp --dport {{ mci_fhir_port }} -j ACCEPT -m comment --comment "MCI FHIR"
  when: iptablesrules.stdout.find("MCI FHIR") == -1

- name: save iptables
  command: service iptables save

- name: Restart
  service: name=mci-fhir state=restarted enabled=yes

- name: Clean existing
  file: path=/tmp/mci-fhir.rpm state=absent
