parameters:
    database_driver: pdo_mysql
    database_host: 127.0.0.1
    database_port: null
    database_name: symfony
    database_user: root
    database_password: null
    mailer_transport: smtp
    mailer_host: 127.0.0.1
    mailer_user: null
    mailer_password: null
    locale: en
    secret: ThisTokenIsNotSoSecretChangeIt
    debug_toolbar: true
    debug_redirects: false
    use_assetic_controller: true
    api_end_point: ~
    location_api_end_point: http://pagani.websitewelcome.com/~stagedgh/dghshrml4/public
    location_auth_key: 9c83d71d41161cbc860380202e43d868ea2b8cc229ed84a2af2ac0818a14cfb4