- name: Add Logstash Repo Key
  rpm_key: key="{{ logstash_repo_key }}" 
           state=present

- name: Enable Elasticsearch repository
  template: src=elasticsearch.repo dest={{ elasticsearch_yum_config}}

- name: Install Elasticsearch from repository
  yum: name=elasticsearch state=latest
  notify:
   - restart elasticsearch