---
- name: Check for remi repository
  stat: path=/etc/yum.repos.d/remi.repo
  register: repo_file

- name: Add repository
  command: rpm -Uvh http://rpms.famillecollet.com/enterprise/remi-release-6.rpm
  when: repo_file.stat.isdir is not defined

- name: Ensure PHP packages are installed
  yum: name={{ item }} state=present enablerepo=remi
  with_items:
    - php
    - php-cli
    - php-common
    - php-devel
    - php-mbstring
    - php-pdo
    - php-pear
    - php-xml
    - php-xmlrpc

- include: composer.yml