---
# defaults file for logstash-role

logstash_python_utils:
 - { package: "python-pycurl" }
 - { package: "python-apt" }

open_jdk: "java-1.7.0-openjdk"
logstash_version: "1.4"

logstash_repo_key: "http://packages.elasticsearch.org/GPG-KEY-elasticsearch"
logstash_yum_config: "/etc/yum.repos.d/logstash.repo"

logstash_packages:
 - { package: "logstash" }
 - { package: "logstash-contrib" }

logstash_conf_dir: "/etc/logstash/conf.d/"

logstash_outputs:
  file: >-
          path => "/var/log/logstash/output.log"