- name: Install packages
  yum: name={{ item }} state=latest
  with_items:
    - python-software-properties
    - wget
    - curl
    - ntp
    - git
    - python-pip
    - unzip
  tags: base

- name: download go agent
  get_url:
    url=http://download.go.cd/gocd-rpm/go-agent-{{ go_server_version}}.noarch.rpm
    dest=/tmp/go-server-{{ go_server_version}}.noarch.rpm

- name: install go agent
  yum: name=/tmp/go-agent-{{ go_server_version}}.noarch.rpm state=present

- name: start go server
  service: name=go-agent enabled=yes state=started

    