- name: Install packages
  yum: name={{ item }} state=latest
  with_items:
    - wget
    - curl
    - ntp
    - git
    - python-pip
    - unzip
    - gcc-c++
    - openssl-devel
    - jq
  tags: base

- name: download go agent
  command: "wget -q -O /tmp/go-agent-{{ go_server_version}}.noarch.rpm --no-check-certificate --no-cookies http://download.go.cd/binaries/{{ go_server_version}}/rpm/go-agent-{{ go_server_version}}.noarch.rpm"

- name: install go agent
  yum: name=/tmp/go-agent-{{ go_server_version}}.noarch.rpm state=present

- name: Set MAVEN_OPTS environment variable
  lineinfile: dest=/etc/default/go-agent regexp='^GO_SERVER_URL=.*' line='GO_SERVER_URL=https://{{ groups['go-server'][0] }}:8154/go'

- name: Allow Go server port through firewall
  iptables: chain=INPUT jump=ACCEPT protocol=tcp  destination_port=8153 comment="GO Agent"

- name: Allow Go Server SSL port through firewall
  iptables: chain=INPUT jump=ACCEPT protocol=tcp  destination_port=8154 comment="GO Agent SSL"

- name: save iptables
  command: service iptables save

- name: start go agent
  service: name=go-agent enabled=yes state=started