- name: Install packages
  yum: name={{ item }} state=latest
  with_items:
    - wget
    - curl
    - ntp
    - git
    - python-pip
    - unzip
    - gcc-c++
    - openssl-devel
    - jq
  tags: base

- name: download go agent
  command: "wget -q -O /tmp/go-agent-{{ go_server_version}}.noarch.rpm --no-check-certificate --no-cookies http://download.go.cd/binaries/{{ go_server_version}}/rpm/go-agent-{{ go_server_version}}.noarch.rpm"

- name: install go agent
  yum: name=/tmp/go-agent-{{ go_server_version}}.noarch.rpm state=present

- name: start go agent
  service: name=go-agent enabled=yes state=started

