
- name: Ensure ansible is installed
  yum: name=ansible1.9 state=latest

- name: Copy the ansible-deploy plugin
  copy:
    src={{location}}/ansible-deploy.sh
    dest=/bin/ansible-deploy
    owner=root group=root mode=755