- name: Clone git-crypt repo
  git: repo=https://github.com/SharedHealth/git-crypt.git dest={{ git_crypt_dir }}

- name: Allow dir access to run user
  file:
    path={{ git_crypt_dir }}
    owner=go
    group=go
    follow=yes
    recurse=yes
    state=directory

- name: Make git-crypt
  shell: "make -C {{ git_crypt_dir }}"

- name: Add git-crypt to path
  sudo: yes
  file:
    src={{ git_crypt_dir}}/git-crypt
    dest=/usr/bin/git-crypt
    owner=go
    group=go
    mode=0755
    state=link
    

