- name: Clone freeshr-playbooks
  git: repo=https://github.com/sharedhealth/FreeSHR-Playbooks.git dest={{ freeshr_playbook_dir }}/FreeSHR-Playbooks

- name: Clone freeshr-bahmni-playbooks
  git: repo=https://github.com/sharedhealth/FreeSHR-Bahmni-Playbooks.git dest={{ freeshr_playbook_dir}}/FreeSHR-Bahmni-Playbooks

- name: Give access to go user
  file: path={{ item }} owner=go group=go recurse=yes
  with_items:
    - "{{ freeshr_playbook_dir }}/FreeSHR-Playbooks"
    - "{{ freeshr_playbook_dir }}/FreeSHR-Bahmni-Playbooks"
