- name: Register iptable rules
  shell: iptables -L
  register: iptablesrules


- name: Allow Opscenter monitoring
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 61620 -j ACCEPT -m comment --comment "OpscenterMonitoring"
  when: iptablesrules.stdout.find("OpscenterMonitoring") == -1

- name: Allow Opscenter agents
  command: /sbin/iptables -I INPUT 1 -p tcp --dport 61621 -j ACCEPT -m comment --comment "OpscenterAgents"
  when: iptablesrules.stdout.find("OpscenterAgents") == -1

- name: save iptables
  shell: iptables-save > /etc/sysconfig/iptables


- name: remove existing agent
  yum: name=datastax-agent state=absent


- name: install agent
  yum: name=datastax-agent state=present


- name: stop agent
  service: name=datastax-agent state=stopped

  
- name: copy configuration
  template:
    src=address.yaml.j2
    dest=/var/lib/datastax-agent/conf/address.yaml
    mode=0644
    owner=root
    group=root
    backup=yes
    
- name: start agent
  service: name=datastax-agent state=started enabled=yes

  