---

- name: Create Destination Directory
  file: path={{ data_destination_dir }} state=directory

- name: Copy Scripts
  copy: src='{{ item }}' dest={{ data_destination_dir }} mode=0644
  with_fileglob:
    - "{{ data_source_dir }}/{{ data_file }}"

- name: Install Data
  shell: "mysql -u terminologies -p{{ tr_mysql_user_password }}  -h 127.0.0.1 terminologies < {{ data_destination_dir }}/{{ data_file }}"

- name: Delete Scripts
  shell: "rm -rf {{ data_destination_dir }}"
