- name: Create group
  user:
    name=bdshr
    state=present
  sudo: yes

- name: Create user
  user: name=bdshr group=bdshr generate_ssh_key=yes ssh_key_bits=2048 state=present password={{ system_user_password }}
  sudo: yes
  tags:
    - update-user

- name: configure sudoers
  lineinfile: "dest=/etc/sudoers state=present backup=yes regexp='^bdshr' insertafter='^# %wheel' line='bdshr ALL=(ALL) NOPASSWD: ALL' validate='visudo -cf %s'"
  sudo: yes

- name: allow bdshr ssh access
  lineinfile:
    dest=/etc/ssh/sshd_config
    backrefs=yes
    backup=yes
    regexp='(^AllowGroups+\s)([\w\- ]+)(?<![bdshr])'
    line='\1\2 bdshr'
  tags:
    - sshd

- name: reload sshd
  service: name=sshd state=reloaded
