---

- name: Checkout MCI-LR code
  git: repo=https://github.com/SharedHealth/MCI-LR.git
    dest={{mci_lr_home}}
    update=yes

- name: Copy Configuration
  copy:
    src=parameters.yml
    dest={{mci_lr_home}}/app/config/parameters.yml

- name: Download all dependencies
  shell: chdir={{mci_lr_home}} /usr/local/bin/composer install

- name: Import Locations
  shell: chdir={{mci_lr_home}} php app/console mci:import:lr -n
